title: Kyuukei Art
description: "Artwork hub for character images, references, and collections."
baseurl: ""  # Set if your site is in a subdirectory
url: "https://yourgithubusername.github.io"  # Replace with your GitHub Pages URL
